### ISSUE TITLE
3D RGBD data instead of 3D Lidar data?

### ISSUE THREAD

**Issue by teamROBI** [snt-arg/lidar_situational_graphs#4]
Hi, in curiosity will it be possible to apply your method with 3D RGBD data inputs in real time?

**Comment by hridaybavle** [comment]
Hello, ideally it could work with RGBD data if you have a source of odometry information. The keyframes would have a point cloud with lower field of view. Because of the lower field of view point cloud, the room detection and loop closure would need to be tuned, but the system should work on an RGBD .

**Comment by hridaybavle** [comment]
Closing this issue. If you have any more issues feel free to open a new ones.
